#!/usr/bin/env bash
set -euo pipefail

meta(){ cat <<'JSON'
{"id":"35_ux_linear","ver":"1.0.0","deps":["30_web_gui"],"desc":"Linear UX landing with role-based dashboards"}
JSON
}

apply(){
  # Idempotency guard: if enhanced UX already exists, skip
  if [[ -f infra/web/dashboard-system.js ]] && [[ -f infra/web/sidebar.js ]]; then
    echo "SKIP 35_ux_linear: enhanced UX already exists" >&2
    return 0
  fi
  mkdir -p infra/web compose.d

  cat > infra/web/nginx.conf <<'NGX'
server {
  listen 80;
  server_name _;
  server_tokens off;
  root /usr/share/nginx/html;
  index index.html;

  location = /login { add_header X-Frame-Options "DENY" always; add_header X-Content-Type-Options "nosniff" always; add_header Referrer-Policy "no-referrer" always; add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always; add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' https://cdn.jsdelivr.net; script-src 'self'; font-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always; add_header Cache-Control "no-store" always; try_files /login.html =404; }
  location = /dashboard { add_header X-Frame-Options "DENY" always; add_header X-Content-Type-Options "nosniff" always; add_header Referrer-Policy "no-referrer" always; add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always; add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' https://cdn.jsdelivr.net; script-src 'self'; font-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always; add_header Cache-Control "no-store" always; try_files /dashboard.html =404; }
  location = /dashboard/user { add_header X-Frame-Options "DENY" always; add_header X-Content-Type-Options "nosniff" always; add_header Referrer-Policy "no-referrer" always; add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always; add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' https://cdn.jsdelivr.net; script-src 'self'; font-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always; add_header Cache-Control "no-store" always; try_files /dashboard-user.html =404; }
  location = /dashboard/admin { add_header X-Frame-Options "DENY" always; add_header X-Content-Type-Options "nosniff" always; add_header Referrer-Policy "no-referrer" always; add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always; add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' https://cdn.jsdelivr.net; script-src 'self'; font-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always; add_header Cache-Control "no-store" always; try_files /dashboard-admin.html =404; }
  location = /admin { add_header Cache-Control "no-store" always; try_files /admin.html =404; }
  location = /admin/modules { add_header Cache-Control "no-store" always; try_files /admin-modules.html =404; }
  location = /advanced { add_header Cache-Control "no-store" always; try_files /advanced.html =404; }
  location ~* ^/(index|login|dashboard|dashboard-user|dashboard-admin|admin|admin-modules|advanced)\.html$ { add_header X-Frame-Options "DENY" always; add_header X-Content-Type-Options "nosniff" always; add_header Referrer-Policy "no-referrer" always; add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always; add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' https://cdn.jsdelivr.net; script-src 'self'; font-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always; add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always; add_header Pragma "no-cache" always; add_header Expires "0" always; }
  location / { add_header X-Frame-Options "DENY" always; add_header X-Content-Type-Options "nosniff" always; add_header Referrer-Policy "no-referrer" always; add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always; add_header Content-Security-Policy "default-src 'self'; connect-src 'self'; img-src 'self' data:; style-src 'self' https://cdn.jsdelivr.net; script-src 'self'; font-src 'self' data:; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always; add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always; add_header Pragma "no-cache" always; add_header Expires "0" always; try_files $uri $uri/ /index.html; }
}
NGX

  cat > infra/web/index.html <<'HTML'
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TPL · Access Portal</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/styles.css" rel="stylesheet"></head><body><main class="container py-4 py-lg-5"><div class="row g-4 align-items-stretch"><section class="col-12 col-lg-7"><div class="card shadow-soft border-0 rounded-4 h-100"><div class="card-body p-4 p-lg-5"><span class="badge text-bg-primary mb-3">TPL Platform</span><h1 class="h3 mb-2" id="heroTitle">Accesso centralizzato e sicuro</h1><p class="text-muted mb-4" id="heroSubtitle">Un unico punto d’ingresso per utenti e amministratori, con dashboard dedicate e navigazione chiara.</p><div class="row g-3"><div class="col-12 col-md-6"><div class="feature-card"><h2 class="h6 mb-1">Esperienza lineare</h2><p class="small text-muted mb-0">Login immediato e redirect automatico alla dashboard per ruolo.</p></div></div><div class="col-12 col-md-6"><div class="feature-card"><h2 class="h6 mb-1">Security by default</h2><p class="small text-muted mb-0">Policy sicure, audit trail e controllo operativo centralizzato.</p></div></div></div></div></div></section><section class="col-12 col-lg-5"><div class="card shadow-soft border-0 rounded-4 h-100"><div class="card-body p-4 p-lg-5 d-flex flex-column"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0" data-i18n="login_title">Accesso</h2><select id="lang" class="form-select form-select-sm lang-select"><option value="it">IT</option><option value="en">EN</option></select></div><div class="vstack gap-2"><label class="small text-muted" for="u" data-i18n="username">Username</label><input class="form-control" id="u" maxlength="64" placeholder="Username"><label class="small text-muted mt-1" for="p" data-i18n="password">Password</label><input class="form-control" id="p" type="password" maxlength="128" placeholder="Password"><button class="btn btn-primary mt-2" id="go" type="button" data-i18n="sign_in">Accedi</button></div><div class="alert alert-info small mt-3 mb-0" id="o">—</div></div></div></section></div></main><script src="/app.js" defer></script><script src="/landing.js" defer></script></body></html>
HTML

  cat > infra/web/login.html <<'HTML'
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/"><title>Redirect</title></head><body></body></html>
HTML

  cat > infra/web/dashboard.html <<'HTML'
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TPL · Dashboard Router</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/styles.css" rel="stylesheet"></head><body><main class="container py-5" style="max-width:760px;"><div class="card shadow-soft border-0 rounded-4"><div class="card-body p-4"><h1 class="h5">Routing dashboard...</h1><p class="text-muted mb-0" id="routerMsg">Verifica ruolo utente in corso.</p></div></div></main><script src="/app.js" defer></script><script src="/dashboard-router.js" defer></script></body></html>
HTML

  cat > infra/web/dashboard-user.html <<'HTML'
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TPL · User Workspace</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/styles.css" rel="stylesheet"></head><body><nav class="navbar nav-pro border-bottom"><div class="container"><a class="navbar-brand fw-semibold" href="/">TPL Workspace</a><div class="ms-auto d-flex gap-2"><button class="btn btn-outline-secondary btn-sm" id="langToggle" type="button">EN</button><button class="btn btn-outline-danger btn-sm" id="lo" type="button" data-i18n="logout">Logout</button></div></div></nav><main class="container py-4 py-lg-5"><div class="row g-4"><section class="col-12 col-xl-4"><div class="card shadow-soft border-0 rounded-4 h-100"><div class="card-body p-4"><h2 class="h6 mb-3" data-i18n="overview">Panoramica</h2><div class="metric-card mb-2"><div class="metric-label">Utente</div><div class="metric-value" id="uName">—</div></div><div class="metric-card mb-2"><div class="metric-label">Ruoli</div><div class="metric-value" id="uRoles">—</div></div><div class="metric-card"><div class="metric-label">Lingua</div><div class="metric-value" id="uLang">—</div></div></div></div></section><section class="col-12 col-xl-8"><div class="card shadow-soft border-0 rounded-4 h-100"><div class="card-body p-4"><h2 class="h6 mb-3" data-i18n="workspace">Workspace</h2><div class="row g-3"><div class="col-12 col-md-6"><a class="btn btn-primary w-100 py-3" href="/advanced">Documentazione</a></div><div class="col-12 col-md-6"><a class="btn btn-outline-primary w-100 py-3" href="/admin" id="adminBtn">Console admin</a></div><div class="col-12"><div class="section-title">Attività recente</div><ul class="list-group list-group-flush" id="activityList"></ul></div></div></div></div></section></div></main><script src="/app.js" defer></script><script src="/dashboard-user.js" defer></script></body></html>
HTML

  cat > infra/web/dashboard-admin.html <<'HTML'
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TPL · Admin Workspace</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="/styles.css" rel="stylesheet"></head><body><nav class="navbar nav-pro border-bottom"><div class="container"><a class="navbar-brand fw-semibold" href="/">TPL Admin Workspace</a><div class="ms-auto d-flex gap-2"><a class="btn btn-outline-primary btn-sm" href="/admin/modules">Moduli</a><button class="btn btn-outline-danger btn-sm" id="lo" type="button" data-i18n="logout">Logout</button></div></div></nav><main class="container py-4 py-lg-5"><div class="row g-4"><section class="col-12 col-lg-4"><div class="card shadow-soft border-0 rounded-4 h-100"><div class="card-body p-4"><h2 class="h6 mb-3">Controllo</h2><div class="metric-card mb-2"><div class="metric-label">Admin</div><div class="metric-value" id="aUser">—</div></div><div class="metric-card mb-2"><div class="metric-label">Auth mode</div><div class="metric-value" id="aAuth">—</div></div><div class="metric-card"><div class="metric-label">Protocollo comm</div><div class="metric-value" id="aComm">HMAC-SHA256</div></div></div></div></section><section class="col-12 col-lg-8"><div class="card shadow-soft border-0 rounded-4"><div class="card-body p-4"><h2 class="h6 mb-3">Operazioni</h2><div class="d-flex flex-wrap gap-2"><button class="btn btn-outline-primary btn-sm" id="reloadAll" type="button">Aggiorna dashboard</button><button class="btn btn-outline-secondary btn-sm" id="sendPing" type="button">Ping sicuro moduli</button></div></div></div><div class="card shadow-soft border-0 rounded-4 mt-3"><div class="card-body p-4"><h2 class="h6 mb-3">Audit sintetico</h2><div id="auditMini" class="small text-muted">Caricamento...</div></div></div><div class="card shadow-soft border-0 rounded-4 mt-3"><div class="card-body p-4"><h2 class="h6 mb-3">Comunicazione moduli</h2><div id="commMini" class="small text-muted">Caricamento...</div></div></div></section></div></main><script src="/app.js" defer></script><script src="/dashboard-admin.js" defer></script></body></html>
HTML

  cat > infra/web/admin.html <<'HTML'
<!doctype html><html lang="it"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/dashboard/admin"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Redirect</title></head><body></body></html>
HTML

  cat > infra/web/app.js <<'JS'
(()=>{const TK="tpl_token",LK="tpl_lang";const H=()=>{const t=sessionStorage.getItem(TK)||"";return t?{Authorization:`Bearer ${t}`}:{}};const S=t=>{if(!t){sessionStorage.removeItem(TK);return;}sessionStorage.setItem(TK,t)};const L=()=>{sessionStorage.removeItem(TK);location.href="/"};const J=async(u,o={})=>{const r=await fetch(u,{...o,headers:{...(o.headers||{}),...H()}});const tx=await r.text();let d=tx;try{d=JSON.parse(tx)}catch(_){}if(!r.ok)throw new Error(typeof d==="string"?d:JSON.stringify(d));return d};const RR=(roles=[])=>roles.includes("admin")?"/dashboard/admin":"/dashboard/user";const SL=(l)=>localStorage.setItem(LK,l||"it");const GL=()=>localStorage.getItem(LK)||"it";const I=async()=>{try{const c=await J(`/api/lang/catalog?lang=${encodeURIComponent(GL())}`),m=c.messages||{};document.querySelectorAll("[data-i18n]").forEach(el=>{const k=el.getAttribute("data-i18n");if(m[k])el.textContent=m[k]});return m}catch(_){return {}}};const SG=async(msg,secret)=>{const p=JSON.stringify(msg.payload||{},Object.keys(msg.payload||{}).sort());const cn=`${msg.sender}|${msg.recipient}|${msg.msg_type}|${p}|${msg.nonce}|${msg.ts}`;const e=new TextEncoder();const k=await crypto.subtle.importKey("raw",e.encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const s=await crypto.subtle.sign("HMAC",k,e.encode(cn));return [...new Uint8Array(s)].map(b=>b.toString(16).padStart(2,"0")).join("")};window.TPL={authHeader:H,setToken:S,logout:L,jsonFetch:J,token:()=>sessionStorage.getItem(TK)||"",roleRoute:RR,setLang:SL,getLang:GL,applyI18n:I,makeCommSignature:SG};})();
JS

  cat > infra/web/landing.js <<'JS'
(()=>{const o=document.getElementById("o"),u=document.getElementById("u"),p=document.getElementById("p"),g=document.getElementById("go"),l=document.getElementById("lang");const m=(t,c="alert-info")=>{o.className=`alert ${c} small mt-3 mb-0`;o.textContent=t};const doLogin=async()=>{m("Login in corso...");const username=(u.value||"").trim(),password=p.value||"";if(!username||!password){m("Inserisci username e password.","alert-warning");return;}try{const d=await TPL.jsonFetch("/api/token",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password})});TPL.setToken(d.access_token||"");const me=await TPL.jsonFetch("/api/me");m("Accesso riuscito. Reindirizzamento...","alert-success");location.href=TPL.roleRoute(me.roles||[])}catch(e){m(`Errore login: ${String(e)}`,"alert-danger")}};g&&g.addEventListener("click",doLogin);p&&p.addEventListener("keydown",e=>{if(e.key==="Enter")doLogin();});l.value=TPL.getLang();l&&l.addEventListener("change",async()=>{TPL.setLang(l.value);await TPL.applyI18n();});(async()=>{await TPL.applyI18n();if(TPL.token()){try{const me=await TPL.jsonFetch("/api/me");location.href=TPL.roleRoute(me.roles||[])}catch(_){TPL.logout();}}})();})();
JS

  cat > infra/web/dashboard-router.js <<'JS'
(()=>{const m=document.getElementById("routerMsg");(async()=>{if(!TPL.token()){location.href="/";return;}try{const me=await TPL.jsonFetch("/api/me");m.textContent="Ruolo verificato, redirect in corso...";location.href=TPL.roleRoute(me.roles||[])}catch(_){TPL.logout();}})();})();
JS

  cat > infra/web/dashboard-user.js <<'JS'
(()=>{const un=document.getElementById("uName"),ur=document.getElementById("uRoles"),ul=document.getElementById("uLang"),al=document.getElementById("activityList"),ab=document.getElementById("adminBtn"),lt=document.getElementById("langToggle"),lo=document.getElementById("lo");const add=t=>{const li=document.createElement("li");li.className="list-group-item small";li.textContent=t;al.appendChild(li)};const rl=async()=>{await TPL.applyI18n();ul.textContent=TPL.getLang().toUpperCase();lt.textContent=TPL.getLang()==="it"?"EN":"IT"};(async()=>{if(!TPL.token()){location.href="/";return;}try{const me=await TPL.jsonFetch("/api/me"),roles=me.roles||[];un.textContent=me.sub||"user";ur.textContent=roles.join(", ")||"user";if(!roles.includes("admin")){ab.classList.add("disabled");ab.setAttribute("aria-disabled","true");}const tp=await TPL.jsonFetch("/api/gui/templates/user_dashboard");add(`Template caricato: ${tp.id}`);add(`Sezioni: ${(tp.sections||[]).map(x=>x.title).join(" · ")}`);const st=await TPL.jsonFetch("/api/status");add(`Sistema operativo: auth=${st.auth}`);add("Sessione pronta.");await rl();}catch(_){TPL.logout();}})();lt&&lt.addEventListener("click",async()=>{TPL.setLang(TPL.getLang()==="it"?"en":"it");await rl();});lo&&lo.addEventListener("click",TPL.logout);})();
JS

  cat > infra/web/dashboard-admin.js <<'JS'
(()=>{const au=document.getElementById("aUser"),aa=document.getElementById("aAuth"),am=document.getElementById("auditMini"),cm=document.getElementById("commMini"),ra=document.getElementById("reloadAll"),sp=document.getElementById("sendPing"),lo=document.getElementById("lo");const raud=(items=[])=>{if(!items.length){am.textContent="Nessun evento audit disponibile.";return;}am.innerHTML=items.slice(-5).reverse().map(x=>`• ${new Date(x.ts*1000).toLocaleString()} — ${x.action} (${x.outcome})`).join("<br>")};const rcom=(items=[])=>{if(!items.length){cm.textContent="Nessuna comunicazione registrata.";return;}cm.innerHTML=items.slice(-5).reverse().map(x=>`• ${x.sender} → ${x.recipient} · ${x.msg_type}`).join("<br>")};const load=async()=>{const me=await TPL.jsonFetch("/api/me");if(!(me.roles||[]).includes("admin"))throw new Error("forbidden");au.textContent=me.sub||"admin";const st=await TPL.jsonFetch("/api/status");aa.textContent=st.auth||"n/a";const ad=await TPL.jsonFetch("/api/audit/logs?limit=20");raud(ad.items||[]);const co=await TPL.jsonFetch("/api/comm/logs?limit=20");rcom(co.items||[])};const ping=async()=>{await TPL.jsonFetch("/api/comm/ping",{method:"POST",headers:{"Content-Type":"application/json"}});await load();};(async()=>{if(!TPL.token()){location.href="/";return;}try{await load();}catch(_){TPL.logout();}})();ra&&ra.addEventListener("click",async()=>{try{await load();}catch(_){TPL.logout();}});sp&&sp.addEventListener("click",async()=>{try{await ping();}catch(e){cm.textContent=`Errore comunicazione: ${String(e)}`;}});lo&&lo.addEventListener("click",TPL.logout);})();
JS

  cat > compose.d/30-web.yml <<'YML'
services:
  web:
    image: nginx:alpine
    volumes:
      - ./infra/web/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./infra/web:/usr/share/nginx/html:ro
    restart: unless-stopped
YML
}

check(){ true; }
rollback(){ true; }
