services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/kc_db_password
    volumes:
      - pg:/var/lib/postgresql/data
      - ${TPL_SECRETS_DIR_HOST:-./.secrets}/keycloak/db_password:/run/secrets/kc_db_password:ro
    networks:
      - kc_internal
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=64M
      - /run/postgresql:size=16M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
      - FOWNER
      - DAC_READ_SEARCH
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
          pids: 100
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        # Read secrets from mounted files into env vars
        export KC_BOOTSTRAP_ADMIN_PASSWORD="$(cat /run/secrets/kc_admin_password)"
        export KC_DB_PASSWORD="$(cat /run/secrets/kc_db_password)"
        exec /opt/keycloak/bin/kc.sh start           --import-realm           --hostname-strict=false           --proxy-headers=forwarded           --http-enabled=true           --http-host=0.0.0.0           --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=false
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: kcadmin
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_USERNAME: keycloak
      KC_HOSTNAME: "${TPL_HOST:-localhost}"
      KC_HTTP_RELATIVE_PATH: /auth
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "false"
    volumes:
      - "./infra/keycloak/realm.json:/opt/keycloak/data/import/realm.json:ro"
      - "${TPL_SECRETS_DIR_HOST:-./.secrets}/keycloak/admin_password:/run/secrets/kc_admin_password:ro"
      - "${TPL_SECRETS_DIR_HOST:-./.secrets}/keycloak/db_password:/run/secrets/kc_db_password:ro"
    networks:
      - default
      - kc_internal
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    # SECURITY: expose (not ports) — only reachable via Docker internal network.
    # Traefik reverse proxy routes /auth/* to keycloak:8080 internally.
    # No host port binding = no direct external access.
    expose:
      - "8080"
    tmpfs:
      - /tmp:noexec,nosuid,size=128M
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /auth/health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 && cat <&3 | head -1 | grep -q '200 OK'"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 768M
          pids: 200

networks:
  kc_internal:
    # Isolated network: only Keycloak and Postgres communicate here.
    # No external access, no other services.
    internal: true

volumes:
  pg:
